#!/bin/bash
yum update

# Install python
yum -y install python3-3.7.6

# Install pip
yum -y install python3-pip-9.0.3

# Install supervisor
pip3 install supervisor==4.1.0

cd /home/ec2-user/python-flask-service

# Install python dev libraries for get_authorized_keys script
pip3 install -r requirements.txt

# Create python virtual environment
python3 -m venv environment

#Activate the virtual environment
source environment/bin/activate

# Install python dev libraries for virtual environment
pip3 install -r requirements.txt

python setup.py install
